worldname: Aleph
firespread_disabled: true
cancel_natural_spawns: true

weathermachines:
  global:
    rain_chance: 0.5
    minimum_rain_duration: 3h
    areas:
      biomes:
       - GLOBAL
daytime_modifier:
  global:
    dayspeed: 0.33
    starting_time: 0
    areas:
      biomes:
       - GLOBAL

monster:
 forestsection:
  updatetime: 15s
  areas:
    biomes:
     - FOREST
     - BEACHES
  mobconfig:
   zombies:
     type: ZOMBIE
     spawn_chance: 0.0666
     identifier: zombie
     maximum_light_level: 7
   skeletons:
     type: SKELETON
     spawn_chance: 0.0666
     identifier: skeleton
     maximum_light_level: 7
   spiders:
     type: SPIDER 
     spawn_chance: 0.0666
     identifier: spiders
     maximum_light_level: 7
   creepers:
     type: CREEPER 
     spawn_chance: 0.0222
     identifier: creeper
     maximum_light_level: 7
   witches:
     type: WITCH
     spawn_chance: 0.0666
     identifier: witch
     maximum_light_level: 7
   enderman:
     type: ENDERMAN
     spawn_chance: 0.0111
     identifier: enderman
     maximum_light_level: 7
   chicken:
     type: CHICKEN
     spawn_chance: 0.2
     identifier: chicken
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
   cow:
     type: COW
     spawn_chance: 0.05
     identifier: cow
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
   horse:
     type: HORSE
     spawn_chance: 0.01
     identifier: horse
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
   pig:
     type: PIG
     spawn_chance: 0.05
     identifier: pig
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
   rabbit:
     type: RABBIT
     spawn_chance: 0.02
     identifier: rabbit
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
   sheep:
     type: SHEEP
     spawn_chance: 0.03
     identifier: sheep
     minimum_light_level: 8
     blocks_to_spawn_on:
      - DIRT
      - GRASS
   OPzombie:
     identifier: opzombie
     type: ZOMBIE
     name: §kFive §4Running §4Ghoul §kFive 
     on_hit_message: Snarl
     spawn_chance: 0.2
     drops:
      Flesh:
       material: ROTTEN_FLESH
       amount: 6
       lore: Human Remains
      Bone:
       material: BONE
       amount: 2
       lore: Human Remains
       enchants:
        KB1:
         enchant: KNOCKBACK
         level: 3
     equipment:
      BluntHotRod:
       material: BLAZE_ROD
       enchants:
        KB8:
         enchant: KNOCKBACK
         level: 8
        S2:
         enchant: DAMAGE_ALL
         level: 2
      firechest451:
       material: LEATHER_CHESTPLATE
       enchants:
        Thorns:
         enchant: THORNS
         level: 3
      firelegs451:
       material: LEATHER_LEGGINGS
       enchants:
        Prot451:
         enchant: PROTECTION_FIRE
         level: 451
      fireBoots154:
       material: LEATHER_BOOTS
       enchants:
        FeatherFall4:
         enchant: PROTECTION_FALL
         level: 4
        Prot451:
         enchant: PROTECTION_FIRE
         level: 451
      helm:
       material: LEATHER_HELMET
       enchants:
        Prot451:
         enchant: PROTECTION_FIRE
         level: 451
     buffs:
      CantDrown:
       type: WATER_BREATHING
       level: 2
      Fast1:
       type: SPEED
       level: 4
     on_hit_debuffs:
      blinded:
       type: BLINDNESS
       level: 2
       duration: 10s
     blocks_to_spawn_on:
      - STONE
      - DIRT
      - GRASS
      - STATIONARY_LAVA
      - STATIONARY_WATER 
      - LEAVES
      - LEAVES_2
      - GRAVEL
      - SAND
      - BEDROCK
      - OBSIDIAN
     blocks_to_spawn_in:
      - AIR
      - STATIONARY_LAVA
      - STATIONARY_WATER 
     health: 100
     despawn_on_chunk_unload: true
     y_spawn_range: 16
   treespider:
     identifier: treespider
     type: SPIDER
     name: §kILL §2Treerantula §kILL 
     on_hit_message: KssssssT
     maximum_light_level: 7
     spawn_chance: 0.1
     drops:
      String:
       material: STRING
       amount: 8
       lore: Sticky Webbing
      FermEye:
       material: FERMENTED_SPIDER_EYE 
       amount: 4
       lore: Rotting Eye
     buffs:
      CantDrown:
       type: WATER_BREATHING
       level: 2
      Slow:
       type: SLOW
       level: 2
      Jump:
       type: JUMP
       level: 3
      Regen:
       type: REGENERATION
       level: 1
      Firerez:
       type: FIRE_RESISTANCE
       level: 2
     on_hit_debuffs:
      Wither:
       type: WITHER
       level: 1
       duration: 5s
      blinded:
       type: BLINDNESS
       level: 1
       duration: 4s
      withered:
       type: CONFUSION
       level: 1
       duration: 10s
     blocks_to_spawn_on:
      - STONE
      - BEDROCK
      - OBSIDIAN
      - DIRT
      - GRASS
      - STATIONARY_LAVA
      - STATIONARY_WATER 
      - LEAVES
      - LEAVES_2
      - GRAVEL
      - CLAY
      - SAND
     blocks_to_spawn_in:
      - AIR
      - STATIONARY_LAVA
      - STATIONARY_WATER 
     health: 100
     despawn_on_chunk_unload: true
     y_spawn_range: 16
   lorax:
     type: SKELETON
     spawn_chance: 0.15
     identifier: lorax
     name: §aDryad
     despawn_on_chunk_unload: false
     maximum_light_level: 7
     drops:
      ironwoodshirt:
       material: CHAINMAIL_CHESTPLATE 
       amount: 1
       lore: Deep roots
       enchants:
        ub2:
         enchant: UNBREAKING
         level: 2
     equipment:
       boomtree:
        material: SAPLING
        enchants:
         KB8:
          enchant: KNOCKBACK
          level: 1
         S2:
          enchant: DAMAGE_ALL
          level: 4
       chainmail:
        material: CHAINMAIL_CHESTPLATE
        enchants:
         Prot451:
          enchant: PROTECTION_FIRE
          level: 50
       fireBoots:
        material: LEATHER_BOOTS
        enchants:
         FeatherFall4:
          enchant: PROTECTION_FALL
          level: 4
         Prot451:
          enchant: PROTECTION_FIRE
          level: 1
     buffs:
       fireres:
              type: FIRE_RESISTANCE
              level: 1
       res:
              type: RESISTANCE
              level: 1
       fast:
              type: SPEED
              level: 1
       CantDrown:
              type: WATER_BREATHING
              level: 2
     on_hit_debuffs:
       burningtouch:
              type: WEAKNESS
              level: 2
              duration: 2s
              chance: 1
     on_hit_message: Stay away from the trees
     deathmessage: For the trees have no tongues 
     blocks_to_spawn_on:
        - BEDROCK
        - OBSIDIAN
        - GRASS
        - DIRT
        - STONE
     blocks_to_spawn_in:
        - AIR
        - STATIONARY_LAVA
        - STATIONARY_WATER 
     health: 100
 riversection:
  updatetime: 10s
  areas:
    biomes:
     - RIVER
  mobconfig:
   squid:
     type: SQUID
     spawn_chance: 0.2
     identifier: squid
     blocks_to_spawn_in:
      - WATER
      - STATIONARY_WATER
 BirchForest:
  updatetime: 1m
  areas:
    biomes:
     - BIRCH_FOREST
     - BIRCH_FOREST_HILLS
  mobconfig:
   OPskeletons:
     identifier: firewatchskelly
     type: SKELETON
     name: §kFive §4RabidFireWatch §kFive 
     spawn_chance: 0.1
     drops:
      PowBone:
       material: BONE
       amount: 6
       lore: Pow wow
       enchants:
        KB1:
         enchant: KNOCKBACK
         level: 1
     equipment:
      BluntHotRod:
       material: BLAZE_ROD
       enchants:
        KB8:
         enchant: KNOCKBACK
         level: 8
        S2:
         enchant: DAMAGE_ALL
         level: 2
      firechest451:
       material: LEATHER_CHESTPLATE
       enchants:
        Prot451:
         enchant: PROTECTION_FIRE
         level: 451
      firelegs451:
       material: LEATHER_LEGGINGS
       enchants:
        Prot451:
         enchant: PROTECTION_FIRE
         level: 451
      fireBoots154:
       material: LEATHER_BOOTS
       enchants:
        FeatherFall4:
         enchant: PROTECTION_FALL
         level: 4
        Prot451:
         enchant: PROTECTION_FIRE
         level: 451
      helm:
       material: LEATHER_HELMET
       enchants:
        Prot451:
         enchant: PROTECTION_FIRE
         level: 451
     buffs:
      CantDrown:
       type: WATER_BREATHING
       level: 2
      Fast1:
       type: SPEED
       level: 1
     on_hit_debuffs:
      RunForestRun:
       type: SPEED
       level: 1
       duration: 1s
      blinded:
       type: BLINDNESS
       level: 1
       duration: 1s
      withered:
       type: WITHER
       level: 1
       duration: 2s
     blocks_to_spawn_on:
      - STONE
      - DIRT
      - GRASS
      - STATIONARY_LAVA
      - STATIONARY_WATER 
      - OBSIDIAN
      - BEDROCK
     blocks_to_spawn_in:
      - AIR
      - STATIONARY_LAVA
      - STATIONARY_WATER 
     health: 320
     despawn_on_chunk_unload: true
     y_spawn_range: 16

